### ISSUE TITLE
Parse error for certain multiple params

### ISSUE THREAD

**Issue by LendaDeAfonselio** [LendaDeAfonselio/Alarm_Bot#114]
```
2021-10-26T06:41:28.755Z - info: An error while trying to add alarm with params: $alarm UTC+8 30 2/12 * * 0,1,2,3,4,5,6 Food Buff <#614417573194498048>
2021-10-26T06:41:28.755Z - error: Unknown alias: nan Error: Unknown alias: nan
    at /home/rsa-key-20210926/Alarm_Bot/node_modules/cron/lib/cron.js:409:11
    at String.replace (<anonymous>)
    at CronTime._parse (/home/rsa-key-20210926/Alarm_Bot/node_modules/cron/lib/cron.js:402:29)
    at new CronTime (/home/rsa-key-20210926/Alarm_Bot/node_modules/cron/lib/cron.js:46:9)
    at new CronJob (/home/rsa-key-20210926/Alarm_Bot/node_modules/cron/lib/cron.js:565:19)
    at Object.execute (/home/rsa-key-20210926/Alarm_Bot/commands/alarm.js:56:52)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Client.<anonymous> (/home/rsa-key-20210926/Alarm_Bot/bot.js:98:21)
```
This was supposed to symbolize the multiples of two until 12 I think

**Comment by LendaDeAfonselio** [comment]
`2021-12-22T18:22:01.597Z - info: An error while trying to add alarm with params: $alarm GMT+8 0 8/12 * * * food buffs`

**Comment by LendaDeAfonselio** [comment]
might be deprecated
