### ISSUE TITLE
Rework exception handling so it does not stop the program from running

### ISSUE THREAD

**Issue by LendaDeAfonselio** [LendaDeAfonselio/Alarm_Bot#126]
When node modules throw exceptions that are not handled properly the whole program comes to a alt.
This makes it so a new shard has to respawn and can lead to discord thinking the bot is spamming logins, which takes the bot down

**Comment by LendaDeAfonselio** [comment]
Errors that are crashing the shards:
```bash
TypeError: Cannot read property 'cache' of undefined
    at MessageCreateAction.handle (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/client/actions/MessageCreate.js:11:41)
    at Object.module.exports [as MESSAGE_CREATE] (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/ubuntu/Alarm_Bot/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/ubuntu/Alarm_Bot/node_modules/ws/lib/websocket.js:1059:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/home/ubuntu/Alarm_Bot/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData (/home/ubuntu/Alarm_Bot/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/home/ubuntu/Alarm_Bot/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/ubuntu/Alarm_Bot/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.socketOnData (/home/ubuntu/Alarm_Bot/node_modules/ws/lib/websocket.js:1153:35)
```

Maybe this one?
```bash
(node:1927) DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
```

**Comment by LendaDeAfonselio** [comment]
```bash
/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/client/actions/Action.js:27
    const existing = manager.cache.get(id);
                             ^
TypeError: Cannot read property 'cache' of undefined
    at MessageUpdateAction.getPayload (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/client/actions/Action.js:27:30)
    at MessageUpdateAction.getMessage (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/client/actions/Action.js:55:12)
    at MessageUpdateAction.handle (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/client/actions/MessageUpdate.js:10:28)
    at Object.module.exports [as MESSAGE_UPDATE] (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_UPDATE.js:6:57)
    at WebSocketManager.handlePacket (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/ubuntu/Alarm_Bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/ubuntu/Alarm_Bot/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/ubuntu/Alarm_Bot/node_modules/ws/lib/websocket.js:1059:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/home/ubuntu/Alarm_Bot/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData (/home/ubuntu/Alarm_Bot/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/home/ubuntu/Alarm_Bot/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/ubuntu/Alarm_Bot/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
```

**Comment by LendaDeAfonselio** [comment]
Ok so I think that this unhandled promisses were because we were not awaiting when sending messages.
Now it should be resolved? fingers crossed 🤞

**Comment by LendaDeAfonselio** [comment]
`MessageCreate.js` from discord js npm package was also changed to:
```js
'use strict';

const Action = require('./Action');
const { Events } = require('../../util/Constants');

class MessageCreateAction extends Action {
  handle(data) {
    const client = this.client;
    const channel = client.channels.cache.get(data.channel_id);
    if (channel && channel.messages && channel.messages.cache) {
      const existing = channel.messages.cache.get(data.id);
      if (existing) return { message: existing };
      const message = channel.messages.add(data);
      const user = message.author;
      let member = message.member;
      channel.lastMessageID = data.id;
      if (user) {
        user.lastMessageID = data.id;
        user.lastMessageChannelID = channel.id;
      }
      if (member) {
        member.lastMessageID = data.id;
        member.lastMessageChannelID = channel.id;
      }

      /**
       * Emitted whenever a message is created.
       * @event Client#message
       * @param {Message} message The created message
       */
      client.emit(Events.MESSAGE_CREATE, message);
      return { message };
    }

    return {};
  }
}

module.exports = MessageCreateAction;

```
to fix the issue while we don't upgrade to 13
