### ISSUE TITLE
Error while trying to validate roles

### ISSUE THREAD

**Issue by LendaDeAfonselio** [LendaDeAfonselio/Alarm_Bot#43]
Stack:
```
2021-01-04T17:33:22.590Z - error: Cannot read property 'hasPermission' of null TypeError: Cannot read property 'hasPermission' of null
    at can_delete_alarm (/root/Alarm_Bot/commands/deletealarm.js:10:28)
    at Object.execute (/root/Alarm_Bot/commands/deletealarm.js:19:14)
    at Client.<anonymous> (/root/Alarm_Bot/bot.js:61:52)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/root/Alarm_Bot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/root/Alarm_Bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/root/Alarm_Bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/root/Alarm_Bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/root/Alarm_Bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/root/Alarm_Bot/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/root/Alarm_Bot/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/root/Alarm_Bot/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/root/Alarm_Bot/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/root/Alarm_Bot/node_modules/ws/lib/receiver.js:143:22)
```

Also related:
```
2021-01-04T18:19:32.021Z - error: Cannot read property 'roles' of null TypeError: Cannot read property 'roles' of null
    at Object.hasAlarmRole (/root/Alarm_Bot/Utils/utility_functions.js:6:28)
    at Object.execute (/root/Alarm_Bot/commands/alarm.js:14:19)
    at Client.<anonymous> (/root/Alarm_Bot/bot.js:61:52)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/root/Alarm_Bot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/root/Alarm_Bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/root/Alarm_Bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/root/Alarm_Bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/root/Alarm_Bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/root/Alarm_Bot/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/root/Alarm_Bot/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/root/Alarm_Bot/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/root/Alarm_Bot/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/root/Alarm_Bot/node_modules/ws/lib/receiver.js:143:22)
```

**Comment by LendaDeAfonselio** [comment]
Let's see if giving the bot permission to manage roles fixes this...
